//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tilde.LuaDebugger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tilde.LuaDebugger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Break {
            get {
                object obj = ResourceManager.GetObject("Break", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BreakedThread {
            get {
                object obj = ResourceManager.GetObject("BreakedThread", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Breakpoint {
            get {
                object obj = ResourceManager.GetObject("Breakpoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrwRefresh {
            get {
                object obj = ResourceManager.GetObject("BrwRefresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Connect {
            get {
                object obj = ResourceManager.GetObject("Connect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;&lt;/title&gt;
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///
        ///.S0 {
        ///	color: #FF0000;
        ///}
        ///.S1 {
        ///	color: #007F00;
        ///	background: #D0F0F0;
        ///	text-decoration: inherit;
        ///	font-size: 9pt;
        ///}
        ///.S2 {
        ///	color: #007F00;
        ///	font-size: 9pt;
        ///}
        ///.S4 {
        ///	color: #007F7F;
        ///}
        ///.S5 {
        ///	color: #00007F;
        ///}
        ///.S6 {
        ///	color: #7F007F;
        ///}
        ///.S10 {
        ///	color: #000000;
        ///}
        ///.S13 {
        ///	color: #00007F;
        ///	background: #D0FFD0;
        ///	text-decoration:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConsoleWindowTemplate {
            get {
                return ResourceManager.GetString("ConsoleWindowTemplate", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap CurrentFrame {
            get {
                object obj = ResourceManager.GetObject("CurrentFrame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Disconnect {
            get {
                object obj = ResourceManager.GetObject("Disconnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EmptyBreakpoint {
            get {
                object obj = ResourceManager.GetObject("EmptyBreakpoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FolderClosed_16x16 {
            get {
                object obj = ResourceManager.GetObject("FolderClosed_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Percentage {
            get {
                object obj = ResourceManager.GetObject("Percentage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Run {
            get {
                object obj = ResourceManager.GetObject("Run", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StartProfile {
            get {
                object obj = ResourceManager.GetObject("StartProfile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon SystrayConnected {
            get {
                object obj = ResourceManager.GetObject("SystrayConnected", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon SystrayDisconnected {
            get {
                object obj = ResourceManager.GetObject("SystrayDisconnected", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tree_closed {
            get {
                object obj = ResourceManager.GetObject("tree_closed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tree_open {
            get {
                object obj = ResourceManager.GetObject("tree_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
